openapi: 3.1.0
info:
  title: Mutant Supreme EN Actions
  version: 2.0.0
servers:
  - url: https://fabricia-mutant-schema.onrender.com

paths:
  /mutate:
    post:
      operationId: mutateText
      summary: Mutação completa de texto PT para EN
      description: >
        Mutação cinematográfica para inglês americano, com ambientação exclusiva em Wilmington, NC.
        Respeitar DNA, Linha do Tempo e Regras Mestres. Executa validações SENTRY (geografia, DNA, atmosfera).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                textoPT:
                  type: string
                  description: Texto em português para mutação
                dna:
                  type: string
                  description: DNA dos personagens (19 fixos)
                timeline:
                  type: string
                  description: (Opcional) Se não informado, será puxado automaticamente do Docs.
                enforceWhitelist:
                  type: boolean
                  default: true
                  description: Se true, só permite topônimos na whitelist de Wilmington (ambientacao.md)
                whitelistOverride:
                  type: array
                  items:
                    type: string
                  description: (Opcional) Itens extras de whitelist para este request
                blacklistOverride:
                  type: array
                  items:
                    type: string
                  description: (Opcional) Itens extras de blacklist para este request
              required:
                - textoPT
                - dna
      responses:
        "200":
          description: Versão mutada com relatório SENTRY estruturado
          content:
            application/json:
              schema:
                type: object
                properties:
                  roteiroEN:
                    type: string
                  aberturaAB:
                    type: array
                    items:
                      type: string
                  shorts:
                    type: array
                    items:
                      type: string
                  relatorioSENTRY:
                    $ref: "#/components/schemas/RelatorioSENTRY"

  /revise:
    post:
      operationId: reviseText
      summary: Revisão cultural de trecho em inglês
      description: Ajusta um trecho em inglês para costumes e expressões americanas e voz neural fluida.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                trechoEN:
                  type: string
                  description: Trecho em inglês a ser revisado
              required:
                - trechoEN
      responses:
        "200":
          description: Trecho revisado
          content:
            application/json:
              schema:
                type: object
                properties:
                  trechoRevisado:
                    type: string

  /ctrtest:
    post:
      operationId: ctrTest
      summary: Teste de CTR para títulos e thumbnails
      description: Analisa título e thumbnail e prevê CTR provável, sugerindo melhorias.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                titulo:
                  type: string
                  description: Título a ser testado
                thumbnailDescricao:
                  type: string
                  description: Descrição ou conceito de thumbnail
              required:
                - titulo
                - thumbnailDescricao
      responses:
        "200":
          description: Relatório preditivo de CTR
          content:
            application/json:
              schema:
                type: object
                properties:
                  ctrPrevisto:
                    type: string
                  sugestaoMelhoria:
                    type: string

components:
  schemas:
    RelatorioSENTRY:
      type: object
      properties:
        status:
          type: string
          enum: [PASS, FAIL]
        resumo:
          type: string
        geografia:
          type: object
          properties:
            whitelistAtivada:
              type: boolean
            locaisDetectados:
              type: array
              items: { type: string }
            foraDaWhitelist:
              type: array
              items: { type: string }
            termosBanidos:
              type: array
              items: { type: string }
        dna:
          type: object
          properties:
            personagensUsados:
              type: array
              items: { type: string }
            personagensNaoAutorizados:
              type: array
              items: { type: string }
            inconsistencias:
              type: array
              items: { type: string }
        atmosfera:
          type: object
          properties:
            elementosAplicados:
              type: array
              items: { type: string }
            faltantes:
              type: array
              items: { type: string }
        cliffhangers:
          type: object
          properties:
            contagem:
              type: integer
            marcasDeTempo:
              type: array
              items: { type: string }
        output:
          type: object
          properties:
            titlesAB:
              type: array
              items: { type: string }
            frasesShorts:
              type: array
              items: { type: string }
        violacoes:
          type: array
          items: { type: string }

x-rules:
  - https://raw.githubusercontent.com/Fabricia07/fabricia-mutant-schema/main/docs/mutacoes.md
  - https://raw.githubusercontent.com/Fabricia07/fabricia-mutant-schema/main/docs/dna.md
  - https://raw.githubusercontent.com/Fabricia07/fabricia-mutant-schema/main/docs/ambientacao.md
  - https://raw.githubusercontent.com/Fabricia07/fabricia-mutant-schema/main/docs/protocolos.md
  - https://raw.githubusercontent.com/Fabricia07/fabricia-mutant-schema/main/docs/regras-mestras.md

# (Opcional) Metadados operacionais para o server ler:
x-wilmington:
  whitelistSource: https://raw.githubusercontent.com/Fabricia07/fabricia-mutant-schema/main/docs/ambientacao.md
  blacklist:
    - Asheville
    - Biltmore
    - Blue Ridge
    - Pack Square
    - Patton Avenue
    - Copacabana
    - Rio
    - Rio de Janeiro
    - Maggie
